apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-java-app.fullname" . }}
  labels:
    {{- include "hello-java-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30011
      protocol: TCP
      name: http
  selector:
    {{- include "hello-java-app.selectorLabels" . | nindent 4 }}
